project:
  type: website
  output-dir: docs

website:
  description: "Personal Website of Steven Mesquiti"
  navbar:
    left:
      - text: Steven Mesquiti
        href: about.qmd  # Redirects to the about page when clicked
    right:
      - text: Home
        href: about.qmd  # Additional link to the about page
      - text: Publications & Preprints
        href: publications.qmd
      - text: CV
        href: CV.qmd
      - text: Posts
        href: posts.qmd
      - text: Coding Guide
        href: coding.qmd
  page-footer:
    left: "© 2025 Steven Mesquiti"
    right: "[MIT License](LICENSE)"
format:
  html:
    theme:
      - cyborg
      - brand
    toc: true
    css: styles.css
editor: visual
