---
title: "Empathy and helping: the role of affect in response to others’ suffering"
categories: [Empathy, Compassion, Positive affect, Prosocial, Social support, Narratives, Helping]
title-block-banner: true
Year: 2025
about:
  template: marquee
  links:
    - text: DOI
      href: https://doi.org/10.1038/s41598-025-87221-2
---

# Abstract

Decades of research hold that empathy is a multifaceted construct. A related challenge in empathy research is to describe how each subcomponent of empathy uniquely contributes to social outcomes. Here, we examined distinct mechanisms through which different components of empathy—Empathic Concern, Perspective Taking, and Personal Distress—may relate to prosociality. Participants (N = 77) watched a prerecorded video of a person sharing an emotional real-life story and provided verbal support in response. The listeners then reported how positive and negative they felt while listening to the story. We found that individuals with greater tendencies to experience Empathic Concern and Perspective Taking felt more positive (e.g., connected, compassionate), whereas those with higher Personal Distress felt more negative (e.g., nervous, anxious) in response to another’s suffering. We also observed indirect relationships between Empathic Concern / Perspective Taking and the tendency to help others through positive affective responses to the other’s suffering. These findings build upon the growing literature that distinguishes different components of empathy and their mechanisms that relate to divergent behavioral consequences. Results also highlight the role of positive affect that may motivate prosociality in the face of others’ suffering.

**Citation**: Kang, Y., Mesquiti, S., Baik, E. S., & Falk, E. B. (2025). Empathy and helping: the role of affect in response to others’ suffering. *Scientific Reports*, 15, 3256. https://doi.org/10.1038/s41598-025-87221-2
