---
title: "Predicting Psychological and Subjective Well-being through Language-based Assessment"
categories: [Well-being, Language-based Assessments, Psychological Well-being, Autonomy, Natural Language Processing, Subjective Well-being, AI-based Transformers]
title-block-banner: true
Year: 2025
about:
  template: marquee
  links:
    - text: DOI
      href: https://doi.org/10.31234/osf.io/jvf2z_v1
---

# Abstract

Well-being is commonly defined in terms of comfort, happiness, functioning, and flourishing. Scholars distinguish between subjective well-being (i.e., perceiving life as pleasant) and psychological well-being (i.e., perceiving life as meaningful). While advances in natural language processing have enabled automated assessments of subjective well-being from language, their ability to capture psychological well-being remains underexplored. Across three studies (one preregistered), we examined how well language-based models predict self-reported subjective and psychological well-being. Participants provided verbal or written responses about their satisfaction with life and autonomy, along with standard questionnaire measures. We used contextual word embeddings from transformer-based models to predict well-being scores. Language-based predictions correlated moderately with questionnaire measures of both constructs (rs = .16–.63) and generalized across well-being domains (rs = .15–.50), though these associations were weaker than previously work (rs = .72–.85). Autonomy was consistently less predictable than satisfaction with life. Comparisons with GPT-3.5 and GPT-4 revealed that both models outperformed BERT in predicting satisfaction with life (r = .71 and .75) and modestly improved predictions of autonomy (rGPT‑4 = .49). Supervised dimension projections revealed that satisfaction with life responses clustered around positive emotion and social themes, whereas autonomy responses showed more individualized linguistic patterns. These findings suggest that language-based tools are well-suited for assessing hedonic well-being but face challenges with more abstract, eudaimonic constructs. Future research should refine modeling approaches to enhance the detection of complex psychological states while striking a balance between interpretability, accuracy, and usability.

**Citation**: Mesquiti, S., Cosme, D., Nook, E. C., Falk, E. B., & Burns, S. (2025). Predicting psychological and subjective well-being through language-based assessment. Preprint.
