---
title: "Analysis of social media language reveals the psychological interaction of three successive upheavals"
categories: [Upheavals, LIWC, Social Media, Reddit, Language, COVID-19, Black Lives Matter, Roe v. Wade]
title-block-banner: true
Year: 2025
about:
  template: marquee
  links:
    - text: DOI
      href: https://doi.org/10.1038/s41598-025-89165-z
    - text: PDF
      href: https://www.nature.com/articles/s41598-025-89165-z.pdf
---

# Abstract

Using social media data, the present study documents how three successive upheavals: the COVID pandemic, the Black Lives Matter (BLM) protests of 2020, and the US Supreme Court decision to overturn Roe v. Wade interacted to impact the cognitive, emotional, and social styles of people in the US. Text analyses were conducted on 45,225,895 Reddit comments from 2,451,289 users and 889,402 news headlines from four news sources. Results revealed significant shifts in language related to self-focus (e.g., first-person singular pronouns), collective-focus (e.g., first-person plural pronouns), negative emotion (anxiety and anger words), and engagement (e.g., discussion of upheaval-related topics) after each event. Language analyses captured how social justice-related upheavals (BLM, Roe v. Wade) may have affected people in different ways emotionally than those that affected them personally (COVID). The onset of COVID was related to people becoming increasingly anxious and people turned inward to focus on their personal situations. However, BLM and the overturning of Roe v. Wade aroused anger and action, as people may have looked beyond themselves to address these issues. Analysis of upheaval-related discussions captured the public’s sustained interest in BLM and COVID, whereas interest in Roe v. Wade declined relatively quickly. Shifts in discussions also showed how events interacted as people focused on only one national event at a time, with interest in other events dampening when a new event occurred. The findings underscore the dynamic nature of culturally shared events that are apparent in everyday online language use.

**Citation**: Mesquiti, S., Seraj, S., Weyland, A. H., Ashokkumar, A., Boyd, R. L., Mihalcea, R., & Pennebaker, J. W. (2025). Analysis of social media language reveals the psychological interaction of three successive upheavals. *Scientific Reports*, 15, 5740. https://doi.org/10.1038/s41598-025-89165-z
